# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import seminar_pb2 as seminar__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in seminar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SeminarStub(object):
    """Definição do serviço com três RPCs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calculate = channel.unary_unary(
                '/seminar.Seminar/Calculate',
                request_serializer=seminar__pb2.NumberOperands.SerializeToString,
                response_deserializer=seminar__pb2.OperationResult.FromString,
                _registered_method=True)
        self.TransformString = channel.unary_unary(
                '/seminar.Seminar/TransformString',
                request_serializer=seminar__pb2.StringMessage.SerializeToString,
                response_deserializer=seminar__pb2.StringResult.FromString,
                _registered_method=True)
        self.ModifyFile = channel.unary_unary(
                '/seminar.Seminar/ModifyFile',
                request_serializer=seminar__pb2.FileOperationRequest.SerializeToString,
                response_deserializer=seminar__pb2.FileOperationResult.FromString,
                _registered_method=True)


class SeminarServicer(object):
    """Definição do serviço com três RPCs
    """

    def Calculate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransformString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeminarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calculate,
                    request_deserializer=seminar__pb2.NumberOperands.FromString,
                    response_serializer=seminar__pb2.OperationResult.SerializeToString,
            ),
            'TransformString': grpc.unary_unary_rpc_method_handler(
                    servicer.TransformString,
                    request_deserializer=seminar__pb2.StringMessage.FromString,
                    response_serializer=seminar__pb2.StringResult.SerializeToString,
            ),
            'ModifyFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyFile,
                    request_deserializer=seminar__pb2.FileOperationRequest.FromString,
                    response_serializer=seminar__pb2.FileOperationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seminar.Seminar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seminar.Seminar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Seminar(object):
    """Definição do serviço com três RPCs
    """

    @staticmethod
    def Calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seminar.Seminar/Calculate',
            seminar__pb2.NumberOperands.SerializeToString,
            seminar__pb2.OperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransformString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seminar.Seminar/TransformString',
            seminar__pb2.StringMessage.SerializeToString,
            seminar__pb2.StringResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seminar.Seminar/ModifyFile',
            seminar__pb2.FileOperationRequest.SerializeToString,
            seminar__pb2.FileOperationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
