# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: seminar.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'seminar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rseminar.proto\x12\x07seminar\"F\n\x0eNumberOperands\x12\x10\n\x08\x66irst_op\x18\x01 \x01(\x05\x12\x11\n\tsecond_op\x18\x02 \x01(\x05\x12\x0f\n\x07op_type\x18\x03 \x01(\x05\"!\n\x0fOperationResult\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1e\n\rStringMessage\x12\r\n\x05input\x18\x01 \x01(\t\"\x1e\n\x0cStringResult\x12\x0e\n\x06output\x18\x01 \x01(\t\"\'\n\x14\x46ileOperationRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"&\n\x13\x46ileOperationResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd6\x01\n\x07Seminar\x12>\n\tCalculate\x12\x17.seminar.NumberOperands\x1a\x18.seminar.OperationResult\x12@\n\x0fTransformString\x12\x16.seminar.StringMessage\x1a\x15.seminar.StringResult\x12I\n\nModifyFile\x12\x1d.seminar.FileOperationRequest\x1a\x1c.seminar.FileOperationResultB\r\xaa\x02\ngrpcServerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seminar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\ngrpcServer'
  _globals['_NUMBEROPERANDS']._serialized_start=26
  _globals['_NUMBEROPERANDS']._serialized_end=96
  _globals['_OPERATIONRESULT']._serialized_start=98
  _globals['_OPERATIONRESULT']._serialized_end=131
  _globals['_STRINGMESSAGE']._serialized_start=133
  _globals['_STRINGMESSAGE']._serialized_end=163
  _globals['_STRINGRESULT']._serialized_start=165
  _globals['_STRINGRESULT']._serialized_end=195
  _globals['_FILEOPERATIONREQUEST']._serialized_start=197
  _globals['_FILEOPERATIONREQUEST']._serialized_end=236
  _globals['_FILEOPERATIONRESULT']._serialized_start=238
  _globals['_FILEOPERATIONRESULT']._serialized_end=276
  _globals['_SEMINAR']._serialized_start=279
  _globals['_SEMINAR']._serialized_end=493
# @@protoc_insertion_point(module_scope)
